test:
    image: python:3.8
  stage: test
  before_script:
    - pip install pytest
    - for d in cdci_*; do ( pip install $d; ); done
  script:
    - for d in cdci_*; do ( cd $d; python -m pytest tests; ); done
  only:
    - staging-1.3
    - ci

docker-build:
  image: docker:stable
  stage: build
  before_script:
    - apk add git openssh make bash
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker info
  script:
    - make push
  only:
    - staging-1.3
    - ci


trigger_deployment:
  stage: .post
  trigger:
    project: cdci/dispatcher/dispatcher-chart
    branch: staging-1.3

  only:
    - staging-1.3
    - ci
