docker-build:
  image: docker:stable
  stage: build
  before_script:
    - apk add git openssh make bash
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker info
  script:
    - make push
  only:
    - staging-1.3
    - ci


trigger_build:
  stage: .post
  trigger: cdci/dispatcher/dispatcher-chart
  only:
    - staging-1.3
